server:
  port: 8081

---
spring:
  profiles: jms-template, jms-listener
# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Artemis properties.
  jms:
    template:
      receive-timeout: 2
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: simetraehcapa
    embedded:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: rabbit

  rabbitmq:
    host: localhost # By default
    port: 5672      # By default
    username: guest # By default
    password: guest # By default
    template:
      receive-timeout: 3000

---
spring:
  profiles: kafka
    
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
#        spring.json.trusted.packages: "tacos.kitchen.model.TacoOrder"
        spring.json.trusted.packages: "*" # TODO figure out