apiVerion: app/v1
kind: Deployment
metadata:
  name: taco-cloud-deploy
  labels:
    app: taco-cloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taco-cloud
  template:
      metadata:
        labels:
          app: taco-cloud
      spec:
        containers:
          - name: taco_cloud-container
            image: taco-cloud17-jmx:0.0.1-SNAPSHOT
            livenessProbe:
              initialDelaySeconds: 2
              periodSeconds: 5
              httpGet:
                path: /actuator/health/liveness
                port: 8080
            readinessProbe:
              initialDelaySeconds: 2
              periodSeconds: 5
              httpGet:
                path: /actuator/health/readiness
                port: 8080